M48
; DRILL file {KiCad 8.0.9-8.0.9-0~ubuntu22.04.1} date 2025-04-03T00:10:28-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-03T00:10:28-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9-8.0.9-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X107.66Y-46.45
X107.66Y-84.55
M30
